### ISSUE TITLE
use of $pluginname/$property vars makes it harder to review code

### ISSUE THREAD

**Issue by danmarsden** [appalachianstate/moodle-local_ganalytics#3]
https://github.com/appalachianstate/moodle-local_ganalytics/blob/master/settings.php#L39

This doesn't follow normal Moodle coding guidelines and makes it harder to review your code to make sure you are storing settings in the right place - might be nice to tidy this up.

(This is not a blocker for approval in the plugins db - feel free to close as "won't fix")

**Comment by woolardfa** [comment]
Will do. But curious to know the reasoning. Seems counter-intuitive.

**Comment by danmarsden** [comment]
It's unnecessary abstraction and doesn't follow moodle coding guidelines. (If this was being reviewed for inclusion in core it would get rejected - but as this is your own code feel free to close as won't fix.)

We see a lot of people taking this further and doing things like this:
$pluginname = "my_plugin"
$DB->get_record($pluginname, array());

The first param in a get_record call is a sql injection vector, so the code reviewer has to go looking for where $pluginname is defined, and make sure it isn't overwritten anywhere strange.

Also - the pluginname should never change in the lifetime of a plugin, so putting it into a variable doesn't give any useful benefits.

It's much faster to review code that follows the same guidelines - if everything is necessarily abstracted it takes a lot longer to trace through and see what is going on.

thanks!

**Comment by woolardfa** [comment]
Understood. I (hopefully) don't take it as far as your example, but I try to reduce the risk of typos in the repeat of the same string value over and over. I've changed it though to be compliant.

**Comment by danmarsden** [comment]
yeah - IDE's do sometimes make it easier to track typos in var names than just string values :-) - It's often a personal preference (there are a lot of moodle coding guidelines I don't like when they stand-alone) - but consistent code that follows a strict guideline helps a massive amount when reviewing code.

**Comment by woolardfa** [comment]
Corrected. Thanks for the input.
